CREATE DATABASE ATIVIDADE;

CREATE TABLE USUARIO (
	ID_USUARIO    NUMERIC(6),
	TIPO          VARCHAR(30),
	NOME          VARCHAR(30),
	SOBRENOME     VARCHAR(30),
	APARTAMENTO   NUMERIC(4),
	BLOCO         NUMERIC(3)
);

SELECT * FROM USUARIO;

INSERT INTO USUARIO VALUES(111,'TESTE','TESTE1','TESTE1',11,1);





/* EXERCÍCIO 1 */

USE ATIVIDADE;  
GO  
	IF NOT EXISTS (SELECT NAME AS TABLE_NAME FROM SYS.TABLES WHERE NAME = 'USUARIO') 
		CREATE TABLE USUARIO(	ID_USUARIO	NUMERIC(6),
								TIPO        VARCHAR(30),
								NOME        VARCHAR(30),
								SOBRENOME   VARCHAR(30),
								APARTAMENTO	NUMERIC(4),
								BLOCO		NUMERIC(3))
	ELSE
		PRINT N'TABELA JÁ EXISTE';
GO





/* EXERCÍCIO 2 */

USE ATIVIDADE;  
GO  
	IF EXISTS (SELECT NAME AS TABLE_NAME FROM SYS.TABLES WHERE NAME = 'USUARIO') 
		INSERT INTO USUARIO VALUES (111,'TESTE','TESTE1','TESTE1',11,1);
	ELSE
		PRINT N'TABELA NÃO EXISTE';
GO
SELECT * FROM USUARIO;





/* EXERCÍCIO 3 */

USE ATIVIDADE;  
GO  
	IF EXISTS (SELECT NAME AS TABLE_NAME FROM SYS.TABLES WHERE NAME = 'USUARIO') 
			DROP TABLE DBO.USUARIO
	ELSE
		PRINT N'A TABELA JÁ FOI EXCLUÍDA';
GO
